plugins {
    id 'com.android.application'
}

android {
    namespace 'com.gpsmerchan.app'
    compileSdk 34

    defaultConfig {
        applicationId 'com.gpsmerchan.app'
        minSdk 26
        targetSdk 34
        versionCode 3
        versionName '2.1'
        buildConfigField 'boolean', 'IS_ADMIN', 'false'
    }

    flavorDimensions 'role'
    productFlavors {
        merchan {
            dimension 'role'
        }
        admin {
            dimension 'role'
            applicationId 'com.gpsmerchan.admin'
            buildConfigField 'boolean', 'IS_ADMIN', 'true'
        }
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core:1.12.0'
}
